sudo: required

services:
  - docker

before_install:
  - docker build -t digitalronin/docker-react -f Dockerfile.dev .

script:
  - docker run digitalronin/docker-react npm run test -- --coverage

deploy:
  on:
    branch: master
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-351222107032"
  bucket_path: "docker-react"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
